---

- name: determine if Java is already installed
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: ping_federate_temp_java_version
  changed_when: ping_federate_temp_java_version.rc != 0
  failed_when: no

- debug: 
    var: ping_federate_temp_java_version


- name: failed if Java is not installed
  fail: 
    msg: Java is not installed
  when: ping_federate_temp_java_version.changed

- name: failed when required java version os not installed
  fail:
    msg: "Java version required >= 1.8 but got {{ ping_federate_temp_java_version.stdout }}"
  when: ping_federate_temp_java_version.stdout is not version_compare(ping_federate_required_java_version, '>=') 

- name: make default directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ping_federate_dir }}"

- name: create pingfederate group
  group: 
    name: "{{ ping_federate_group }}"
    state: present

- name: create pingfederate user
  user:
    name: "{{ ping_federate_user }}"
    groups: "{{ ping_federate_group }}"

- name: get if pingfederate run file found
  stat:
    path: "{{ ping_federate_dir }}/bin/run.sh"
  register: stat_result


- name: if run file found == installed
  set_fact: 
    ping_federate_is_installed: true
  when: stat_result.stat.exists


# - name: detect previous ping federate version installed
  

# install firewalld
- name: install firewalld
  package:
    name: "{{item}}"
  with_items:
    - firewalld
    - firewall-config

