---
# This playbook deploys Java SDK to specified host on AWS.

- hosts: "{{ host_name | default('tag_Name_*_sso*') }}"
  roles:
     - { role: java }
  become: yes
  become_method: sudo
  remote_user: ansible
