---
# This playbook deploys Jenkins and Firewalld to specified host on AWS.

- hosts: "{{ host_name | default('tag_Name_*_jenkins*') }}"
  roles:
     - { role: jenkins }
  become: yes
  become_method: sudo
  remote_user: ansible