---
# This playbook attaches a server or group of servers to AD.

- hosts: "{{server_groups}}"
  vars_files:
    - "inventories/{{ env }}/group_vars/all.yml"
  roles:
    - role: base
    - role: dns
    - role: linux_active_directory
  become: yes
  become_method: sudo
  remote_user: ansible
