---
# This playbook deploys sumologic collectors to specified server_groups in a specific environment.

- hosts: "{{server_groups}}"
  remote_user: root
  become: yes
  become_method: sudo
  roles:
    - reset_password
