---
# tasks file for linux_active_directory

- include: install.yml
  tags:
    - install

- include: linux7_config.yml
  when: ansible_distribution_major_version == "7"
  tags:
    - linux7_config

- include: linux6_config.yml
  when: ansible_distribution_major_version == "6"
  tags:
    - linux6_config

- include: custom_sudoers.yml