---

- name: start firewalld
  service:
    name: firewalld
    enabled: yes
    state: started

- name: open port 8080 for Tomcat
  firewalld:
    zone: public
    port: 8080/tcp
    permanent: yes
    state: enabled
    immediate: yes
  notify: 
    - restart firewalld