ntp_daemon: ntpd
ntp_tzdata_package: tzdata
ntp_driftfile: /var/lib/ntp/drift
ntp_enabled: true
ntp_manage_config: true
ntp_servers:
  - "10.10.62.10"
  - "10.16.60.10"      # use ip or fully qualified domian name of the ntp servers 
ntp_restrict:
  - "127.0.0.1"
  - "::1"