- name: restart jenkins
  service:
    name: jenkins
    state: restarted

- name: restart firewalld
  service:
    name: firewalld
    state: restarted

- name: Check if Jenkins is accessible
  wait_for: host=10.232.39.110 port=8080 timeout=10