---

apache_service: httpd
apache_restart_state: restarted
apache_server_root: "/etc/httpd"
apache_modules_dir: "{{apache_server_root}}/modules"
apache_conf_path: /etc/httpd/conf.d
server_domain_name: localhost
apache_server_name: "{{ ansible_hostname }}.{{ server_domain_name }}"
apache_selinux: 
  setsebool: 
    "httpd_can_network_connect": yes

## Used by internal processing
apache_folder_to_create:
  - "{{ apache_server_root }}/ssl.key"
  - "{{ apache_server_root }}/ssl.crt"

apache_remove_default_file:
  - "{{ apache_conf_path }}/autoindex.conf"
  - "{{ apache_conf_path }}/ssl.conf"
  - "{{ apache_conf_path }}/userdir.conf"
  - "{{ apache_conf_path }}/welcome.conf"

apache_certificates: {}

apache_extra_modules:
  weblogic_module: 
    file: weblogic-12c/*
    library: 'modules/mod_wl_24.so'
    setype: httpd_modules_t
  usertrack_module:
    library: 'modules/mod_usertrack.so'
  speling_module:
    library: modules/mod_speling.so
  suexec_module:
    library: modules/mod_suexec.so

apache_listen_port: 80
apache_listen_port_ssl: 443

# libsemanage-python for selinux ansible module
# policycoreutils-python for sefcontext ansible module
apache_packages:
  - httpd
  - httpd-devel
  - mod_ssl
  - openssh
  - libsemanage-python  
  - mod_evasive
#  - mod_security
  - policycoreutils-python

apache_packages_install_mod_jk: 0
apache_packages_mod_jk:
  - gcc
  - gcc-c++ 
  - autoconf
  - libtool

apache_mod_jk_install_dir: /tmp/mod_jk
apache_mod_jk_src_name: tomcat-connectors-1.2.46-src
apache_mod_jk_src_ext: .tar.gz

apache_mod_jk_worker_properties:
  "airline_site1": 
      type: ajp13
      host: hostname1
      port: 8009
      lbfactor: 5
  "airline_site2": 
      type: ajp13
      host: hostname2
      port: 8010
      lbfactor: 10



apache_user: apache
apache_group: apache
apache_serveradmin: root@localhost
apache_documentroot: "/var/www/html"

apache_server_token: ProductOnly
apache_timeout: 120
apache_keep_alive: "Off"
apache_max_keep_alive: 100
apache_keep_alive_timeout: 15
apache_use_conical_name: "Off"

apache_directory:
  "/": 
    AllowOverride: none
    Require: all denied
  "/var/www/html":
      Options: FollowSymLinks
      AllowOverride: None
      Require: all granted
  "/var/www/error":
      AllowOverride: None
      Options: IncludesNoExec
      AddOutputFilter: Includes html
      AddHandler: type-map var
      Require: all granted
      LanguagePriority: en es de fr
      ForceLanguagePriority: Prefer Fallback

apache_ifmodule:
  "prefork.c":
    StartServers: 8
    MinSpareServers: 5
    MaxSpareServers: 20
    ServerLimit: 256
    MaxClients: 256
    MaxRequestsPerChild: 4000
  "worker.c":
    StartServers: 2
    MaxClients: 1024
    MinSpareThreads: 25
    MaxSpareThreads: 75
    ThreadsPerChild: 25
    MaxRequestsPerChild: 0
  "mod_userdir.c":
    UserDir: disable
  "mod_mime_magic.c":
    MIMEMagicFile: conf/magic
  "mod_dav_fs.c":
    DAVLockDB: /var/lib/dav/lockdb

apache_alias:
  "/error/": "/var/www/error/"

apache_extra_config_single_value:
  DirectoryIndex: index.html index.html.var
  AccessFileName: .htaccess
  TypesConfig: /etc/mime.types
  DefaultType: text/plain
  HostnameLookups: "Off"
  ServerSignature: "Off"
  UseCanonicalName: "Off"
  TraceEnable: "Off"
  FileETag: "None"
  AddOutputFilter: INCLUDES .shtml
  AddHandler: type-map var
  ProxyPreserveHost: "On"
  RequestReadTimeout: "header=5-10,MinRate=500 body=20,MinRate=500"

apache_extra_config_multiple_value:
  SetEnv: 
    - 'force-proxy-request-1.0 1'
    - 'proxy-nokeepalive 1'
  ErrorDocument:
    - '403 /noindex.html'
    - '404 /noindex.html'

apache_location: {}


apache_error_log: logs/error_log
apache_log_level: warn
apache_log_config: |

    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %T/%D" combined
    <IfModule logio_module>
        LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
    </IfModule>
    LogFormat "%h %l %u %t \"%r\" %>s %b" common
    LogFormat "%{Referer}i -> %U" referer
    LogFormat "%{User-agent}i" agent
    CustomLog "logs/access_log" combined

apache_proxy:
  extra:
    ProxyRequests: "Off"
    ProxyErrorOverride: "On"
    ProxyTimeout: 3600
    ProxyBadHeader: Ignore
  proxy: |
      Order deny,allow
      Allow from all
      RewriteEngine On
      RewriteCond %{HTTPS} off
      RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [R,NE]
  proxypass:
    "/errorpages/":  "!"
    "/apierrorpagelogo.png": "!"
    "/": http://localhost/
  proxypass_reverse: 
    "/": http://localhost/
  proxypassmatch: {}
    
apache_ssl:
  Listen: 443 https 
  SSLPassPhraseDialog: exec:/usr/libexec/httpd-ssl-pass-dialog
  SSLSessionCache: shmcb:/run/httpd/sslcache(512000)
  SSLSessionCacheTimeout: 300
  SSLRandomSeed: 
    startup: file:/dev/urandom  256
    connect: builtin
  SSLCryptoDevice: builtin
  virtual_hosts: 
    "_default_:443":
      Header: 'always set Strict-Transport-Security "max-age=63072000; includeSubdomains;"'
      ErrorLog: logs/ssl_error_log
      LogLevel: warn
      SSLProtocol: all -SSLv2 -SSLv3 -TLSv1 -TLSv1.1
      SSLCipherSuite: ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
      SSLCertificateFile: /etc/pki/tls/certs/localhost.crt
      SSLCertificateKeyFile: /etc/pki/tls/private/localhost.key
      SSLCompression: "off"
      SSLSessionTickets: "off"
      SSLHonorCipherOrder: "on" 
      CustomLog: 
        "logs/ssl_access_log": 'combined env=!dontlog'
        "logs/ssl_request_log": '"%t %h %{SSL_PROTOCOL}x %{SSL_CIPHER}x \\\"%r\\\" %b" env=!dontlog'
      SetEnvIf:
        'User-Agent "ELB-HealthChecker/2.0"': dontlog
        'User-Agent ".*MSIE.*"': nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
      BrowserMatch: 
        "MSIE [2-5]": nokeepalive ssl-unclean-shutdown downgrade-1.0 force-response-1.0
      files: 
        '~ "\.(cgi|shtml|phtml|php3?)$"': 
          SSLOptions: +StdEnvVars
      directory: 
        "/var/www/cgi-bin": 
          SSLOptions: +StdEnvVars
      extra: ""

apache_proxy_noindex_url: http://client3.apihotels.com/ACESAIR

# mod_evasive parameters
proxy_alerts_webhook: https://hooks.slack.com/services/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
apache_evasive:
  doshashtablesize: 3097
  dospagecount: 5
  dospageinterval: 1
  dossitecount: 50
  dossiteinterval: 1
  dosblockingperiod: 30
  dossystemcommand: 'curl -X POST --data \"payload={\\\"text\\\": \\\"MOD_EVASIVE on {{ansible_hostname}} blocked IP: %s\\\"}\" {{proxy_alerts_webhook}}'
  doswhitelist:
    - 192.168.*.*
    - 10.16.*.*
    - 10.10.*.*
    - 10.65.*.*
