---

# remove previously added entries for loopback line; all hostnames will be added via the local ip address
- name: ensure {{ansible_hostname}}.{{server_domain_name}} is in the /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: '^127\.0\.0\.1 {{ansible_hostname}}.{{server_domain_name}} {{ansible_hostname}} localhost'
    line: "127.0.0.1 localhost localhost.localdomain localhost4 localhost4.localdomain4"
    owner: root
    group: root
    mode: 0644

- debug: 
    msg: "{{ ansible_default_ipv4.address }}"

- name: ensure {{ansible_hostname}}.{{ad_domain_name}} is in the /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: "{{ ansible_facts[base_default_ethernet]['ipv4']['address'] }}\t{{ ansible_hostname }}.{{ad_domain_name}}"
    line: "{{ ansible_facts[base_default_ethernet]['ipv4']['address'] }}\t{{ ansible_hostname }}.{{ad_domain_name}}\t{{ansible_hostname}}.{{server_domain_name}}\t{{ansible_hostname}}"
    state: present
    backup: yes
  when: ansible_facts[base_default_ethernet] is defined and ansible_facts[base_default_ethernet]['ipv4']['address'] is defined

- name: ensure {{ansible_hostname}}.{{ad_domain_name}} is in the /etc/hosts file
  lineinfile:
    path: /etc/hosts
    regexp: "{{ ansible_default_ipv4.address }}\t{{ ansible_hostname }}.{{ad_domain_name}}"
    line: "{{ ansible_default_ipv4.address }}\t{{ ansible_hostname }}.{{ad_domain_name}}\t{{ansible_hostname}}.{{server_domain_name}}\t{{ansible_hostname}}"
    state: present
    backup: yes
  when: ansible_facts[base_default_ethernet] is not defined or ansible_facts[base_default_ethernet]['ipv4']['address'] is not defined